### PR TITLE
Update to PHP version 7.1 via pantheon.upstream.yml. Set filemount at webroot

### LINKED ISSUE #9: Set PHP to version 7
Since we will shortly have a `pantheon.yml` file I recommend we set the PHP version to PHP 7 for new Backdrop sites on Pantheon. 

One note: I added a this setting to an existing Backdrop site and it upgraded the pantheon instance to PHP 7. I'm not sure what ramifications that may have for existing Backdrop sites on Pantheon if we blanket updated them all, but my site was fine.

### PR DESCRIPTION
**Pull request by herbdool**
Fixes #9 and #10

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
Looks good. You could also use a `files` entry in your .gitignore

**Comment by herbdool** [comment]
There's already a /files entry in .gitignore. Thanks Greg.

**Comment by herbdool** [comment]
@kreynen this is the other issue that should be hopefully relatively easy to review.

**Comment by kreynen** [comment]
@herbdool I was testing this yesterday when Pantheon had their outage.  

The first thing I did was test cherry pick this into our existing upstream and deploy to the existing sites that already had the commit from https://github.com/backdrop-ops/backdrop-pantheon/issues/9 applied.  That worked as expected in that it didn't alter the version of PHP we had already defined.

status_report___university_of_colorado_web_developers

Then I cherry-picked the commit into the master of my personal backdrop-pantheon fork and created an upstream from that.

screen shot 2018-09-05 at 1 48 39 pm

Creating new sites from that upstream works as expected in that the version of PHP is now 7.1.21 and the site-specific pantheon.yml is created when the containers are instantiated.  

screen shot 2018-09-06 at 10 00 14 am

That upsteam was still on 1.9.6.

status_report___appserver-c859adf2

So I then merged master from https://github.com/backdrop-ops/backdrop-pantheon into my branch and the upstream update showed up in the Pantheon dashboard as expected.

screen shot 2018-09-06 at 10 18 31 am

Unfortunately I couldn't merge that because the pantheon.yml that gets created conflicts with what I had merged from https://github.com/jenlampton/backdrop-pantheon/commit/bfd6a62d29bdb3a37645da6ae7f2aa7e5ca474a9

screen shot 2018-09-06 at 10 19 27 am

Reverting that commit fixed the conflict and the upstream update applied cleanly.

So the only issue with adding the pantheon.upstream.yml I see would be with new installs from an upstream where someone is using a fork with the pantheon.yml in the upstream codebase.  Since https://github.com/backdrop-ops/backdrop-pantheon/pull/14 wasn't merged and we are happy to remove bfd6a62d29bdb3a37645da6ae7f2aa7e5ca474a9 from our upstream, I think this would only potentially be an impact @jenlampton.  From other threads, I don't think she's using a custom upstream so I'd consider this RTBC.

**Comment by herbdool** [comment]
Thanks for the RTBC @kreyen! Let's see if @serundeputy or @quicksketch can merge this now.

**Comment by serundeputy** [comment]
Looks good thanks @herbdool, @greg-1-anderson and @kreynen!
merging.

**Pull request merged**
