### PR TITLE
Passing Pantheon DB Settings to Backdrop

### PR DESCRIPTION
**Pull request by populist**
Here is the initial commit for the Pantheon specific settings, similar to how we are dealing with Drupal 7 and 8. 

The issues that I see that still need to be addressed include:

-- Users are not automatically directed to /core/install.php when the site needs to be installed due to the existence of the database settings already being present. This is handled by a hack in index.php for D8, but might be able to be done more smartly. 

-- After what I think is a successful site installation, users are given the message "The website encountered an unexpected error. Please try again later.". Not sure where that comes from, but needs some more digging.

-- Handling of the CMI's active directory. I know this changed a bit with Drupal 8, so want to make sure we have a good implementation running here.

### CODE REVIEW

**Comment by populist** [comment]
I went ahead and updated the settings today. As per Jen's comment above, several things were able to be removed (core redirect, CMI, settings verification, database injection logic) since that is handled by Backdrop.

Of the remaining three items, I think in the fullness of time we can get rid of all of these as well because realistically Pantheon should be able to inject appropriately named values for settings ($SERVER['BACKDROP_SETTINGS'] and $hash_salt) and should be able to support a file mount at /files instead of /sites/default/files. 

In the near term, an approach like this should work however I am seeing a couple fatal errors that crop up with this pull request including (Fatal error: Call to undefined function config_get() and Fatal error: Call to undefined function menu_get_custom_theme() ) which cause trouble.

**Comment by jenlampton** [comment]
I was able to reproduce the `Fatal error: Call to undefined function menu_get_custom_theme()` only when I was using an out-of-date version of settings.php.  Stashing my changes and checking out a fresh copy of settings.php, then adding my changes back eliminated that Fatal.  I'm not sure why that's error is the one that appeared - definitely weird.  But think a new settings.php will solve it for you.

I also got `undefined function config_get()` when I was trying to use `$config->set

**Comment by jenlampton** [comment]
Se also: https://github.com/backdrop/backdrop-issues/issues/563

**Comment by populist** [comment]
Alright! We made a few more changes on our side and this should be GOOD TO GO. At present all we do is pass the DB settings to Backdrop in cases where the user is running on Pantheon which is good enough to get it all running with proper files directory and hash values and such.

**Pull request merged**
